[package]
name = "bpx"
version = "0.1.0"
authors = ["Yuri Edward <yuri6037@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.0.7"
byteorder = "1"
xz = "0.1.0"

[profile.dev]
opt-level = 1
overflow-checks = false
